PunktDe:
  OAuth2:
    Server:
      grantTypes:
        client_credentials:
          enabled: false
        authorization_code:
          enabled: false
        implicit:
          enabled: false
        password:
          enabled: false

      scopes: []
      authenticationPageUri: '?forwardUrl=/oauth/approveauthorization'
